version: "3.5"
services:
  www:
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./src:/var/www/html/
    links:
      - db
    networks:
      - default
  db:
    image: mysql:5.7.13
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: alatella
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test